server:
  port: 8081

spring:
  application:
    name: auth-service

  cloud:
    config:
      enabled: false

  config:
    import: 
      - "optional:file:.env[.properties]"
      - "optional:file:../.env[.properties]"

  datasource:
    url: ${AUTH_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3307/auth_db}
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: cse.supriya.kumari@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

springdoc:
  api-docs:
    path: /api/auth/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security: DEBUG
    com.smartsure.auth: DEBUG

management:
  tracing:
    sampling:
      probability: 0.0
    enabled: false
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans