server:
  port: 8080

spring:
  application:
    name: api-gateway

  config:
    import: "optional:configserver:http://localhost:8888"

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authService
                fallbackUri: forward:/fallback/auth

        - id: policy-service
          uri: lb://policy-service
          predicates:
            - Path=/api/policies/**
          filters:
            - name: CircuitBreaker
              args:
                name: policyService
                fallbackUri: forward:/fallback/policy

        - id: claims-service
          uri: lb://claims-service
          predicates:
            - Path=/api/claims/**
          filters:
            - name: CircuitBreaker
              args:
                name: claimsService
                fallbackUri: forward:/fallback/claims

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**
          filters:
            - name: CircuitBreaker
              args:
                name: adminService
                fallbackUri: forward:/fallback/admin

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false

jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /api/auth/v3/api-docs
      - name: policy-service
        url: /api/policies/v3/api-docs
      - name: claims-service
        url: /api/claims/v3/api-docs
      - name: admin-service
        url: /api/admin/v3/api-docs

logging:
  level:
    com.smartsure.gateway: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers