server:
  port: 8083

spring:
  application:
    name: claims-service

  config:
    import: 
      - "optional:configserver:http://localhost:8888"
      - "optional:file:.env[.properties]"
      - "optional:file:../.env[.properties]"

  datasource:
    url: jdbc:mysql://localhost:3306/claims_db
    username: root
    password: ${DB_PASSWORD}

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: ${RABBITMQ_PASSWORD:guest}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

file:
  upload-dir: uploads/claims

springdoc:
  api-docs:
    path: /api/claims/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.smartsure.claims: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50

management:
  tracing:
    enabled: false
    sampling:
      probability: 0.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers