server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/cse-supriya-kumari/SmartSure-Config-Server
          default-label: main
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,env

  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.config.server: INFO